window.XQ = window.XQ || {};

window.XQ.Config = {
  version: "1.2.10",
  files: 9,
  ranks: 10,
  labels: {
    r: { K: "帅", A: "仕", B: "相", N: "马", R: "车", C: "炮", P: "兵", S: "主", Q: "后" },
    b: { K: "将", A: "士", B: "象", N: "马", R: "车", C: "炮", P: "卒", S: "主", Q: "后" },
    n: { G: "草" },
  },
  values: { K: 900, Q: 120, R: 90, S: 55, C: 45, N: 40, B: 20, A: 20, P: 12, G: 0 },
  redSetup: [
    ["R", 0, 9], ["N", 1, 9], ["B", 2, 9], ["A", 3, 9], ["K", 4, 9],
    ["A", 5, 9], ["B", 6, 9], ["N", 7, 9], ["R", 8, 9],
    ["C", 1, 7], ["C", 7, 7], ["P", 0, 6], ["P", 2, 6],
    ["P", 4, 6], ["P", 6, 6], ["P", 8, 6],
  ],
  blackCore: [["A", 3, 0], ["K", 4, 0], ["A", 5, 0]],
  blackAddOrder: [
    ["P", 4, 3], ["B", 2, 0], ["C", 1, 2], ["N", 1, 0],
    ["R", 0, 0], ["P", 2, 3], ["B", 6, 0], ["C", 7, 2],
    ["N", 7, 0], ["R", 8, 0], ["P", 6, 3], ["P", 0, 3], ["P", 8, 3],
  ],
  randomItems: [
    { id: "guard", name: "铁壁营", rarity: "white", text: "敌方吃子评分降低，AI 更保守。", stacks: false },
    { id: "cannon", name: "神机炮", rarity: "green", text: "每件使击破车约 +11、马约 +5、炮约 +5 即时积分。", stacks: true },
    { id: "scout", name: "斥候图", rarity: "purple", text: "提示会标出一个高价值走法。", stacks: false },
    { id: "oracle", name: "问策签", rarity: "green", text: "每件使提示消耗积分降低 20%。", stacks: true },
    { id: "supply", name: "粮草车", rarity: "gold", text: "立即获得额外积分。", stacks: true },
    { id: "shopFree", name: "免刷新券", rarity: "purple", text: "接下来三次可付费商店刷新免费。", stacks: true },
    { id: "kingGuard", name: "护驾符", rarity: "red", text: "将帅首次被吃时免疫，并反杀吃将帅的棋子。", stacks: true },
    { id: "pawnSpell", name: "贬卒符", rarity: "purple", text: "选择敌方一个非将帅棋子变为卒。", stacks: true },
    { id: "banner", name: "破阵旗", rarity: "red", text: "每面提高过关基础积分，多面旗帜加算。", stacks: true },
    { id: "revive", name: "归阵令", rarity: "gold", text: "取回一个被吃掉的己方棋子放在己方半场；空格归阵不消耗行动，拾取道具时消耗一次红方行动。", stacks: true },
    { id: "rabbitFoot", name: "兔脚", rarity: "gold", text: "己方棋子被吃时，若后方一格为空，则后跳避开吃子；触发后冷却 4 回合。", stacks: false, shopOnly: true, unlock: "rabbitFoot" },
    { id: "turtleShell", name: "龟壳", rarity: "red", text: "红帅首次被吃时龟缩避险，进入 3 回合无敌，9 回合后重新生效。", stacks: false, shopOnly: true, unlock: "turtleShell" },
    { id: "endure", name: "卧薪尝胆", rarity: "gold", text: "己方棋子被吃后，红方下一回合额外行动 1 次，最多累积 1 次。", stacks: false, shopOnly: true, unlock: "endure" },
    { id: "charmMakeup", name: "媚妆", rarity: "red", text: "消耗品。红方下一枚被吃的棋子阵亡后，吃子的黑方棋子转投红方。", stacks: true, shopOnly: true, unlock: "charmMakeup" },
    { id: "meteor", name: "飒沓流星", rarity: "red", text: "消耗品。购买后立即作用于当前红方回合，每吃一个黑子增加一次行动；首次未吃子时效果失效，先走完原有行动，再由黑方连续行动 3 步。", stacks: true, shopOnly: true },
    { id: "offboard", name: "盘外招", rarity: "gold", text: "消耗品。购买后双方剩余棋子立即进入弹幕战；红帅可拾取冻符使黑方冻结 1 秒，红帅阵亡则战败。", stacks: true, shopOnly: true },
    { id: "riverFlood", name: "河界汛期", rarity: "gold", text: "本关河界出现河内线。双方棋子跨河前必须先停到河内线；从河内线开始的行动不受限制。", stacks: true, shopOnly: true },
    { id: "elephantRiver", name: "飞象渡河", rarity: "purple", text: "象可过河，仍走田字；持有象时更易出现。", stacks: false },
    { id: "rookPhoenix", name: "车化凤辇", rarity: "red", text: "车可沿斜线移动最多 4 格，仍不能越子。", stacks: false },
    { id: "elephantStep", name: "象位移", rarity: "gold", text: "象除走田字外，可选横竖移动一格。", stacks: false },
    { id: "horseStep", name: "马位移", rarity: "purple", text: "马除走日字外，可选横竖移动一格。", stacks: false },
    { id: "horseLeap", name: "马腾跃", rarity: "gold", text: "马走日字时不再受蹩马腿限制。", stacks: false, requires: "horseStep" },
    { id: "horseRun", name: "马驰骋", rarity: "red", text: "马可额外横竖移动两格。", stacks: false, requires: "horseLeap" },
    { id: "horseFly", name: "马踏飞燕", rarity: "red", text: "马可额外横竖移动三格。", stacks: false, requires: "horseRun" },
    { id: "advisorRiver", name: "仕过河", rarity: "gold", text: "仕可过河，可走横竖斜一格；持有仕时更易出现。", stacks: false, requires: "advisorFree" },
    { id: "advisorStride", name: "仕途通达", rarity: "red", text: "仕可横竖斜移动两格，且可越子。", stacks: false, shopOnly: true, unlock: "advisorStride", requires: "advisorRiver" },
    { id: "advisorFree", name: "仕出宫", rarity: "green", text: "仕可出宫，在己方半场斜走一格。", stacks: false },
    { id: "strongPawn", name: "强兵", rarity: "purple", text: "兵卒过河前也可横向移动。", stacks: false },
    { id: "elitePawn", name: "精兵", rarity: "gold", text: "兵卒可斜走一格。", stacks: false, requires: "strongPawn" },
    { id: "kingFree", name: "将帅出宫", rarity: "red", text: "帅可出宫，在己方半场横竖一格。", stacks: false },
    { id: "kingRiver", name: "将帅过河", rarity: "gold", text: "将帅可过河，在全盘横竖移动一格。", stacks: false, requires: "kingFree" },
  ],
  rarityOrder: ["white", "green", "purple", "gold", "red"],
  rarityWeights: { white: 1, green: 0.82, purple: 0.58, gold: 0.34, red: 0.14 },
  shopWeightBonuses: { offboard: 3 },
  consumableIds: ["supply", "shopFree", "letMove", "pawnSpell", "destroy", "donate", "kingGuard", "revive", "meteor", "offboard", "riverFlood", "charmMakeup"],
};
